USE QL_DH_GH
GO
CREATE PROC CHANGE_PASSWORD
	@IDTaiKhoan Char(5) ,
	@Password Char(20)
	
AS
BEGIN TRANSACTION
		BEGIN TRY
			IF NOT EXISTS ( SELECT * FROM TAIKHOAN WHERE TAIKHOAN.IDTaiKhoan = @IDTaiKhoan)
				BEGIN
					PRINT N'TÀI KHOẢN KHÔNG TỒN TẠI'
					ROLLBACK TRANSACTION
					RETURN 1
				END
		END TRY
		BEGIN CATCH
			PRINT N'LỖI HỆ THỐNG'
			ROLLBACK
			RETURN 1
		END CATCH
	UPDATE TAIKHOAN
	SET Password = @Password
	WHERE IDTaiKhoan = @IDTaiKhoan
	COMMIT TRANSACTION
	RETURN 0
go

CREATE PROC Sp_NV_LayTongTinTK
	@USERNAME VARCHAR(10),
	@PASSWORD VARCHAR(20)
AS
BEGIN TRAN
SET TRANSACTION ISOLATION LEVEL Repeatable read
	BEGIN TRY	
	--kiểm tra tài khoản có tồn tại hay không
	IF not exists (SELECT   TK.IDTaiKhoan        
                FROM TAIKHOAN tk
                WHERE TK.Username=@USERNAME AND TK.Password=@PASSWORD)
	BEGIN
		WAITFOR DELAY '00:00:20'
		PRINT N'Tài Khoản Không Tồn Tại'
		ROLLBACK TRAN
		RETURN 1
	END	
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRANSACTION
		RETURN 1

	END CATCH
	SELECT * FROM TAIKHOAN WHERE TAIKHOAN.Username=@USERNAME AND TAIKHOAN.Password=@PASSWORD 
	COMMIT TRANSACTION
GO