use QL_DH_GH
go

CREATE PROCEDURE DT_UPDATEPRICE_MON1 
@IDMon ChAR(5), @GiaMon MONEY
AS
BEGIN TRAN 
	BEGIN TRY
		IF NOT EXISTS (SELECT GiaMon FROM MON WHERE IDMon=@IDMon)
		BEGIN
			PRINT N'ID MÓN KHÔNG TỒN TẠI'
			ROLLBACK TRANSACTION
			RETURN 1
		END
		
		WAITFOR DELAY '0:0:10'
		SELECT * FROM MON WITH(UPDLOCK) WHERE IDMon=@IDMon
		UPDATE MON SET GiaMon=@GiaMon WHERE IDMon=@IDMon
		COMMIT TRANSACTION
		RETURN 0
		END TRY
		BEGIN CATCH
			PRINT N'LỖI HỆ THỐNG'
			ROLLBACK TRAN
			RETURN 1
		END CATCH
GO		

CREATE PROCEDURE DT_UPDATEPRICE_MON2
@IDMon ChAR(5), @GiaMon MONEY
AS
BEGIN TRAN 
	BEGIN TRY
		IF NOT EXISTS (SELECT GiaMon FROM MON WHERE IDMon=@IDMon)
		BEGIN
			PRINT N'ID MÓN KHÔNG TỒN TẠI'
			ROLLBACK TRANSACTION
			RETURN 1
		END
		
		SELECT * FROM MON WHERE IDMon=@IDMon
		UPDATE MON SET GiaMon=@GiaMon WHERE IDMon=@IDMon
		COMMIT TRANSACTION
		RETURN 0
		END TRY
		BEGIN CATCH
			PRINT N'LỖI HỆ THỐNG'
			ROLLBACK TRAN
			RETURN 1
		END CATCH
